 
MACRO(EXTRACT_FILENAME INPUT OUTPUT)
	STRING(REGEX REPLACE ".*/(.*)$" "\\1" ${OUTPUT} "${INPUT}" )
ENDMACRO(EXTRACT_FILENAME INPUT OUTPUT)


MACRO(ECHO_RESOURCES RESOURCESINPUTS)
	FOREACH(source ${RESOURCESINPUTS})
		EXTRACT_FILENAME(${source} filename)
		#SET(RESOURCES_OUTPUTS ${RESOURCES_OUTPUTS} ${CMAKE_CURRENT_BINARY_DIR}/${filename})
		MESSAGE(STATUS "ECHO: copy " ${source} " to " ${CMAKE_CURRENT_BINARY_DIR}/${filename})
	ENDFOREACH(source)
ENDMACRO(ECHO_RESOURCES RESOURCESINPUTS)

MACRO(COPY_RESOURCES RESOURCES_INPUTS RESOURCES_OUTPUTS)
	SET(OUTPUTS "")
	FOREACH(source ${RESOURCES_INPUTS})
		EXTRACT_FILENAME(${source} filename)
		SET(OUTPUTS ${OUTPUTS} ${CMAKE_CURRENT_BINARY_DIR}/${filename})
		MESSAGE(STATUS "copy " ${source} " to " ${CMAKE_CURRENT_BINARY_DIR}/${filename})
	
		ADD_CUSTOM_COMMAND(
			OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${filename}
			COMMAND ${CMAKE_COMMAND} -E copy ${source} ${CMAKE_CURRENT_BINARY_DIR}/${filename}
			WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
		)
	ENDFOREACH(source)
	SET(RESOURCES_OUTPUTS ${OUTPUTS})
ENDMACRO(COPY_RESOURCES RESOURCES_INPUTS RESOURCES_OUTPUTS)
